### ISSUE TITLE
Improvment: Precise Volume

### ISSUE THREAD

**Issue by mmaret** [jonathanklee/VolumeLockr#1]
On my phone, (Moto Z2), even the lower sound setting could be quite loud.
That's why I've try an application such as "Precise Volume" which allow me to tweak a fine volume level.
But this application is full off ads and not open source.
So I've tried to add this functionality to your great application... But I did not succeed ... I did not seems possible to do so with AudioManager.

As I'm sure that your are a better Android and Kotlin developer, you may find out how to add a cool feature to your app :)

**Comment by jonathanklee** [comment]
I played a bit with the Precise Volume application. It does not seem to do what it says it does (:
